// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyUpdatedBot.Infrastructure.Data;

#nullable disable

namespace MyUpdatedBot.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260118162705_AddChatSettingsEntity")]
    partial class AddChatSettingsEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyUpdatedBot.Core.Models.Entities.ChatSettingsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<bool>("LinksAllowed")
                        .HasColumnType("bit");

                    b.Property<bool>("SpamProtectionEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("ChatSettings");
                });

            modelBuilder.Entity("MyUpdatedBot.Core.Models.Entities.MessageCountEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("MessageCount")
                        .HasColumnType("int");

                    b.Property<string>("Rank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserRefId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserRefId");

                    b.ToTable("MessageStats");
                });

            modelBuilder.Entity("MyUpdatedBot.Core.Models.Entities.ReputationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<long>("UserRefId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserRefId", "ChatId")
                        .IsUnique();

                    b.ToTable("RatingStats");
                });

            modelBuilder.Entity("MyUpdatedBot.Core.Models.Entities.ReputationGivenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("FromUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastGiven")
                        .HasColumnType("datetime2");

                    b.Property<long>("ToUserRefId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId", "ToUserRefId", "ChatId")
                        .IsUnique();

                    b.ToTable("ReputationGivens");
                });

            modelBuilder.Entity("MyUpdatedBot.Core.Models.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyUpdatedBot.Core.Models.Entities.WarningRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("UserRefId")
                        .HasColumnType("bigint");

                    b.Property<int>("WarningsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("UserRefId", "ChatId")
                        .IsUnique();

                    b.ToTable("WarningRecords");
                });

            modelBuilder.Entity("MyUpdatedBot.Core.Models.Entities.MessageCountEntity", b =>
                {
                    b.HasOne("MyUpdatedBot.Core.Models.Entities.UserEntity", "User")
                        .WithMany("MessageStats")
                        .HasForeignKey("UserRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyUpdatedBot.Core.Models.Entities.ReputationEntity", b =>
                {
                    b.HasOne("MyUpdatedBot.Core.Models.Entities.UserEntity", "User")
                        .WithMany("RatingStats")
                        .HasForeignKey("UserRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyUpdatedBot.Core.Models.Entities.WarningRecord", b =>
                {
                    b.HasOne("MyUpdatedBot.Core.Models.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyUpdatedBot.Core.Models.Entities.UserEntity", b =>
                {
                    b.Navigation("MessageStats");

                    b.Navigation("RatingStats");
                });
#pragma warning restore 612, 618
        }
    }
}
