//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUpdatedBot.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyUpdatedBot.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add to group.
        /// </summary>
        internal static string AddToGroupButton {
            get {
                return ResourceManager.GetString("AddToGroupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You&apos;ve already rolled the dice.
        /// </summary>
        internal static string AlreadyRolled {
            get {
                return ResourceManager.GetString("AlreadyRolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⛔ Ban.
        /// </summary>
        internal static string BanButton {
            get {
                return ResourceManager.GetString("BanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to ban the user. Please check the bot&apos;s permissions..
        /// </summary>
        internal static string BotCouldntBanUser {
            get {
                return ResourceManager.GetString("BotCouldntBanUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to mute the user. Check the bot&apos;s permissions..
        /// </summary>
        internal static string BotCouldntMuteUser {
            get {
                return ResourceManager.GetString("BotCouldntMuteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to change the word..
        /// </summary>
        internal static string CallbackQuery_CantChangeWord {
            get {
                return ResourceManager.GetString("CallbackQuery_CantChangeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New word.
        /// </summary>
        internal static string CallbackQuery_NewWord {
            get {
                return ResourceManager.GetString("CallbackQuery_NewWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Word.
        /// </summary>
        internal static string CallbackQuery_Word {
            get {
                return ResourceManager.GetString("CallbackQuery_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to verify your permissions.
        /// </summary>
        internal static string CantCheckRights {
            get {
                return ResourceManager.GetString("CantCheckRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can&apos;t complain about yourself.
        /// </summary>
        internal static string CantComplYourself {
            get {
                return ResourceManager.GetString("CantComplYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Couldn&apos;t get the list of administrators. Please try again later..
        /// </summary>
        internal static string CantGetAdminsList {
            get {
                return ResourceManager.GetString("CantGetAdminsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change word.
        /// </summary>
        internal static string ChangeWordButton {
            get {
                return ResourceManager.GetString("ChangeWordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat settings.
        /// </summary>
        internal static string ChatSettings_Title {
            get {
                return ResourceManager.GetString("ChatSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на minutes ago
        ///Selected action:.
        /// </summary>
        internal static string ChosenAction {
            get {
                return ResourceManager.GetString("ChosenAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your language is English 🇬🇧.
        /// </summary>
        internal static string ChosenLanguage {
            get {
                return ResourceManager.GetString("ChosenLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complaint against:.
        /// </summary>
        internal static string ComplaintAgainst {
            get {
                return ResourceManager.GetString("ComplaintAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complaint from:.
        /// </summary>
        internal static string ComplaintFrom {
            get {
                return ResourceManager.GetString("ComplaintFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The complaint was ignored.
        /// </summary>
        internal static string ComplaintIgnored {
            get {
                return ResourceManager.GetString("ComplaintIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚠️ Complaint in the chat:.
        /// </summary>
        internal static string ComplaintIn {
            get {
                return ResourceManager.GetString("ComplaintIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The complaint has already been processed by admin.
        /// </summary>
        internal static string ComplaintProcessed {
            get {
                return ResourceManager.GetString("ComplaintProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The complaint has been sent to the administrators. Thank you..
        /// </summary>
        internal static string ComplaintSent {
            get {
                return ResourceManager.GetString("ComplaintSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на has finished the game. To start a new one, type.
        /// </summary>
        internal static string Crocodile_EndedGame {
            get {
                return ResourceManager.GetString("Crocodile_EndedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time&apos;s up! To start a new game, send.
        /// </summary>
        internal static string Crocodile_TimesUp {
            get {
                return ResourceManager.GetString("Crocodile_TimesUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End the game.
        /// </summary>
        internal static string EndGameButton {
            get {
                return ResourceManager.GetString("EndGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚠️ Unable to check the game&apos;s status. Please try again later..
        /// </summary>
        internal static string Error_CrocodileState {
            get {
                return ResourceManager.GetString("Error_CrocodileState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred during processing. Please try again..
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The event has been suspended.
        /// </summary>
        internal static string EventStopped {
            get {
                return ResourceManager.GetString("EventStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The game is over.
        /// </summary>
        internal static string GameAlreadyEnded {
            get {
                return ResourceManager.GetString("GameAlreadyEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚠️ The game is already started in this chat..
        /// </summary>
        internal static string GameAlreadyStarted {
            get {
                return ResourceManager.GetString("GameAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guessed the word! The correct answer is:.
        /// </summary>
        internal static string GuessedWord {
            get {
                return ResourceManager.GetString("GuessedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Host.
        /// </summary>
        internal static string HostIs {
            get {
                return ResourceManager.GetString("HostIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ➖ Ignore.
        /// </summary>
        internal static string IgnoreButton {
            get {
                return ResourceManager.GetString("IgnoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language is.
        /// </summary>
        internal static string LanguageButton {
            get {
                return ResourceManager.GetString("LanguageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow links.
        /// </summary>
        internal static string LinksAllowedButton {
            get {
                return ResourceManager.GetString("LinksAllowedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To use all of the bot&apos;s features, add it to your chat.
        /// </summary>
        internal static string MessageAfterChooseLang {
            get {
                return ResourceManager.GetString("MessageAfterChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔇 Mute 30 mins.
        /// </summary>
        internal static string MuteButton {
            get {
                return ResourceManager.GetString("MuteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You need to type this command in response to a message that violates the chat rules.
        /// </summary>
        internal static string NeedMessageForReport {
            get {
                return ResourceManager.GetString("NeedMessageForReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _No participants yet_.
        /// </summary>
        internal static string NoParticipantsYet {
            get {
                return ResourceManager.GetString("NoParticipantsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are not an administrator of this chat..
        /// </summary>
        internal static string NotAdmin {
            get {
                return ResourceManager.GetString("NotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only admins can change settings.
        /// </summary>
        internal static string OnlyAdminsCanChange {
            get {
                return ResourceManager.GetString("OnlyAdminsCanChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only the host can change the word!.
        /// </summary>
        internal static string OnlyHostChangeWord {
            get {
                return ResourceManager.GetString("OnlyHostChangeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only the host can end the game!.
        /// </summary>
        internal static string OnlyHostEndGame {
            get {
                return ResourceManager.GetString("OnlyHostEndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only the host can see the word.
        /// </summary>
        internal static string OnlyHostSeeWord {
            get {
                return ResourceManager.GetString("OnlyHostSeeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The other participants.
        /// </summary>
        internal static string OtherParticipants {
            get {
                return ResourceManager.GetString("OtherParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processed by the admin.
        /// </summary>
        internal static string ProcessedByAdmin {
            get {
                return ResourceManager.GetString("ProcessedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Roll 🎲.
        /// </summary>
        internal static string RollButton {
            get {
                return ResourceManager.GetString("RollButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click “Roll 🎲” to roll the dice.
        ///Seconds left: .
        /// </summary>
        internal static string RollDice {
            get {
                return ResourceManager.GetString("RollDice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show word.
        /// </summary>
        internal static string ShowWordButton {
            get {
                return ResourceManager.GetString("ShowWordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flood protection.
        /// </summary>
        internal static string SpamProtectionButton {
            get {
                return ResourceManager.GetString("SpamProtectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The contest has begun! Organizer.
        /// </summary>
        internal static string StartEvent {
            get {
                return ResourceManager.GetString("StartEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Let&apos;s play “Crocodile”! Host: .
        /// </summary>
        internal static string StartTheGamePart1 {
            get {
                return ResourceManager.GetString("StartTheGamePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click the “Show Word” button
        ///
        ///Each round lasts *15* minutes.
        /// </summary>
        internal static string StartTheGamePart2 {
            get {
                return ResourceManager.GetString("StartTheGamePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop ⛔️.
        /// </summary>
        internal static string StopButton {
            get {
                return ResourceManager.GetString("StopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на seconds left before submitting the next complaint.
        /// </summary>
        internal static string TimeLeftForNextCompl {
            get {
                return ResourceManager.GetString("TimeLeftForNextCompl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To start a new game, click:.
        /// </summary>
        internal static string ToStartNewGame {
            get {
                return ResourceManager.GetString("ToStartNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown command.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Until the end.
        /// </summary>
        internal static string UntilTheEnd {
            get {
                return ResourceManager.GetString("UntilTheEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The user has been banned..
        /// </summary>
        internal static string UserBanned {
            get {
                return ResourceManager.GetString("UserBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на has been blocked (by the administrator)..
        /// </summary>
        internal static string UserBannedByAdmin {
            get {
                return ResourceManager.GetString("UserBannedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The user has been muted for 30 minutes.
        /// </summary>
        internal static string UserMuted {
            get {
                return ResourceManager.GetString("UserMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на was muted for 30 minutes (by the administrator&apos;s decision)..
        /// </summary>
        internal static string UserMutedByAdmin {
            get {
                return ResourceManager.GetString("UserMutedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your throw.
        /// </summary>
        internal static string UserThrow {
            get {
                return ResourceManager.GetString("UserThrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello! Thanks for adding me.
        ///Please select a language for this chat.
        /// </summary>
        internal static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Winners:.
        /// </summary>
        internal static string WinnersEvent {
            get {
                return ResourceManager.GetString("WinnersEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect data.
        /// </summary>
        internal static string WrongData {
            get {
                return ResourceManager.GetString("WrongData", resourceCulture);
            }
        }
    }
}
