//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUpdatedBot.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyUpdatedBot.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add to group.
        /// </summary>
        internal static string AddToGroupButton {
            get {
                return ResourceManager.GetString("AddToGroupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to change the word..
        /// </summary>
        internal static string CallbackQuery_CantChangeWord {
            get {
                return ResourceManager.GetString("CallbackQuery_CantChangeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New word.
        /// </summary>
        internal static string CallbackQuery_NewWord {
            get {
                return ResourceManager.GetString("CallbackQuery_NewWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Word.
        /// </summary>
        internal static string CallbackQuery_Word {
            get {
                return ResourceManager.GetString("CallbackQuery_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change word.
        /// </summary>
        internal static string ChangeWordButton {
            get {
                return ResourceManager.GetString("ChangeWordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat settings.
        /// </summary>
        internal static string ChatSettings_Title {
            get {
                return ResourceManager.GetString("ChatSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your language is English 🇬🇧.
        /// </summary>
        internal static string ChosenLanguage {
            get {
                return ResourceManager.GetString("ChosenLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на has finished the game. To start a new one, type.
        /// </summary>
        internal static string Crocodile_EndedGame {
            get {
                return ResourceManager.GetString("Crocodile_EndedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time&apos;s up! To start a new game, send.
        /// </summary>
        internal static string Crocodile_TimesUp {
            get {
                return ResourceManager.GetString("Crocodile_TimesUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End the game.
        /// </summary>
        internal static string EndGameButton {
            get {
                return ResourceManager.GetString("EndGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚠️ Unable to check the game&apos;s status. Please try again later..
        /// </summary>
        internal static string Error_CrocodileState {
            get {
                return ResourceManager.GetString("Error_CrocodileState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚠️ The game is already started in this chat..
        /// </summary>
        internal static string GameAlreadyStarted {
            get {
                return ResourceManager.GetString("GameAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guessed the word! The correct answer is:.
        /// </summary>
        internal static string GuessedWord {
            get {
                return ResourceManager.GetString("GuessedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Host.
        /// </summary>
        internal static string HostIs {
            get {
                return ResourceManager.GetString("HostIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language is.
        /// </summary>
        internal static string LanguageButton {
            get {
                return ResourceManager.GetString("LanguageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow links.
        /// </summary>
        internal static string LinksAllowedButton {
            get {
                return ResourceManager.GetString("LinksAllowedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To use all of the bot&apos;s features, add it to your chat.
        /// </summary>
        internal static string MessageAfterChooseLang {
            get {
                return ResourceManager.GetString("MessageAfterChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only admins can change settings.
        /// </summary>
        internal static string OnlyAdminsCanChange {
            get {
                return ResourceManager.GetString("OnlyAdminsCanChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only the host can change the word!.
        /// </summary>
        internal static string OnlyHostChangeWord {
            get {
                return ResourceManager.GetString("OnlyHostChangeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only the host can end the game!.
        /// </summary>
        internal static string OnlyHostEndGame {
            get {
                return ResourceManager.GetString("OnlyHostEndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only the host can see the word.
        /// </summary>
        internal static string OnlyHostSeeWord {
            get {
                return ResourceManager.GetString("OnlyHostSeeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show word.
        /// </summary>
        internal static string ShowWordButton {
            get {
                return ResourceManager.GetString("ShowWordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flood protection.
        /// </summary>
        internal static string SpamProtectionButton {
            get {
                return ResourceManager.GetString("SpamProtectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Let&apos;s play “Crocodile”! Host: .
        /// </summary>
        internal static string StartTheGamePart1 {
            get {
                return ResourceManager.GetString("StartTheGamePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click the “Show Word” button
        ///
        ///Each round lasts *15* minutes.
        /// </summary>
        internal static string StartTheGamePart2 {
            get {
                return ResourceManager.GetString("StartTheGamePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To start a new game, click:.
        /// </summary>
        internal static string ToStartNewGame {
            get {
                return ResourceManager.GetString("ToStartNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown command.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello! Thanks for adding me.
        ///Please select a language for this chat.
        /// </summary>
        internal static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome_Title", resourceCulture);
            }
        }
    }
}
